### ISSUE TITLE
Position.fromLatLng returns a reversed Position object

### ISSUE THREAD

**Issue by bh3605** [microsoft/Maps#9] opened 2024-01-12 19:06 UTC
Since you guys don't have a github repo for the javascript sdk I'm going to start filing issues in this samples project.

A Position object is nothing but a number array of [longitude, latitude]. The atlas.data.Position.fromLatLng() returns an array of [latitude, longitude].

A position on the map is represented [longitude, latitude] as given by this position in the eastern US.
![image](https://github.com/microsoft/Maps/assets/3073436/50c34aac-853a-4eab-8669-0d3c3a8bd1f0)

I have a list of geocoordinates and I'll reverse geocode them, but first I'll make my life a little easier and convert them to a position object using Position.fromLatLng(). Problem is the returned Position object is backwards.

![image](https://github.com/microsoft/Maps/assets/3073436/8437e20d-30c8-4582-8252-36d4a6afcc48)

When I use this array in the reverseGeocode method I'll get a position in Antarctica instead of the US. It would be great if the fromLatLng method returned the correct Position object. Maybe just create a new one called fromLngLat().

**Comment by rbrundritt** [comment] 2024-01-12 19:21
Digging into the source code it appears this error only occurs when you pass in individual values like fromLatLng(lat, lng). However, if you pass in an array with values [lat, lng] or an object with lat/lng, latitude/longitude, y/x properties, it works as intended. This bug appears to have been there since the initial release in 2018 (6 years) and likely went unnoticed as I don't think I've came across anyone passing in the individual values since it takes less code to just make a simple array. I'll log the bug with the team, but would recommend simply reversing your values, wrapping with square brackets to make them an array and not use the fromLatLng function.

**Comment by rbrundritt** [comment] 2024-01-12 19:28
Closing this thread as this is not the right place to report issues to any map platform. 

For Azure Maps issues, please report issues using one of the following methods in the future:

- Raise it for discussion on the Azure Maps forums: https://learn.microsoft.com/en-us/answers/tags/209/azure-maps
- Report it in the Azure Portal under your Azure Maps resource by raising a support ticket.

**Closed as completed by rbrundritt** 2024-01-12 19:28 UTC
